server:
  port: 8123
  servlet:
    context-path: /api/interface/

spring:
  application:
    name: api-interface
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

