# 公共配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, yupi
      routes:
        - id: api_interface
          uri: http://localhost:8123
          predicates:
            - Path=/api/interface/**
        - id: api_route
          uri: http://localhost:8080
          predicates:
          - Path=/api/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080,http://localhost:8000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: yuapi-gateway
    qosEnableL: true
  protocol:
    name: dubbo
  registry:
    address: nacos://leikooo.icu:8848